Enable GC loading from a shared library
ruby/ruby pull request #10456
Opened 2024-04-04 19:53 UTC by eightbitraptor

This PR replaces https://github.com/ruby/ruby/pull/10302 as a method for dynamically loading a shared GC library. This new approach has been guided by feedback from @kateinoigakukun and @nobu 

The approach taken here is as follows:

- Enable this feature by configuring with `--with-shared-gc`
- When enabled, Ruby will check for the presence of the environment variable `RUBY_GC_LIBRARY_PATH`
- If that path exists and points to a valid shared object
  - Open the shared object (using `dln_open`), and map the `Init_GC` function to a function map
  - call `Init_GC` as part of `rb_objspace_alloc` when initialising the GC
- If that path does not point to a valid shared object
  - Degrade gracefully to initialising the existing Ruby objspace and GC
  
When Ruby is configured without the `--with-shared-gc` flag, no extra code is compiled and so existing behaviour is maintained without any performance penalty.

Enabling this feature, but not populating `RUBY_GC_LIBRARY_PATH` will incur a small performance penalty due to the overhead of using `getenv` to check for the environment variable.

The use of `dln.c` rather than using `dlopen` directly, should enable this feature to be supported on all platforms that support loading shared libraries, rather than the initial implementation, which explicitly only supported Linux and MacOS.

2024-04-05 00:29 UTC, nobu commented on gc.c
> +            "ruby_external_gc_init: Shared library %s cannot be opened.\n",
`rb_bug` appends a newline.
```suggestion
            "ruby_external_gc_init: Shared library %s cannot be opened.",
```

2024-04-05 00:29 UTC, nobu commented on gc.c
> +        rb_bug("ruby_external_gc_init: Init_GC func not exported by library");
The failing shared library path is not needed?

```suggestion
        rb_bug("ruby_external_gc_init: Init_GC func not exported by library %s.",
            gc_so_path);
```

2024-04-05 00:29 UTC, nobu commented on dln.h
> +void * dln_open(const char *file);
```suggestion
void *dln_open(const char *file);
```

2024-04-05 00:29 UTC, nobu commented on configure.ac
> +config_summary "enable shared GC"    "$gc_support"
Why not `$with_shared_gc`?

2024-04-05 23:03 UTC, kateinoigakukun approved these changes

2024-04-06 06:10 UTC, nobu requested changes

2024-04-06 06:10 UTC, nobu commented on tool/m4/ruby_shared_gc.m4
> +    AC_DEFINE([USE_SHARED_GC], [0])
This `gc_support` word feels like GC is not opted out if it is "no".

```suggestion
    AC_MSG_RESULT([yes])
    AC_DEFINE([USE_SHARED_GC], [1])
], [
    AC_MSG_RESULT([no])
    with_shared_gc="no"
    AC_DEFINE([USE_SHARED_GC], [0])
```

2024-04-06 06:10 UTC, nobu commented on configure.ac
> +config_summary "with shared GC"      "$gc_support"
```suggestion
config_summary "with shared GC"      "$with_shared_gc"
```

2024-04-15 18:50 UTC, merged