[Universal parser] Decouple IMEMO from rb_ast_t
ruby/ruby pull request #10618
Opened 2024-04-24 08:20 UTC by hasumikin

This patch removes the `VALUE flags` member from the `rb_ast_t` structure making `rb_ast_t` no longer an IMEMO object.

## Background

We are trying to make the Ruby parser generated from parse.y a universal parser that can be used by other implementations such as mruby. To achieve this, it is necessary to exclude VALUE and IMEMO from parse.y, AST, and NODE.

## Summary (file by file)

- `rubyparser.h`
  - Remove the `VALUE flags` member from `rb_ast_t`
- `ruby_parser.c` and `internal/ruby_parser.h`
  - Introduce a TypedData_Wrap_Struct VALUE which wraps `rb_ast_t` so that GC can manage it (see ``) - You can retrieve `rb_ast_t` from the VALUE by `rb_ruby_ast_data_get()`
  - Change the return type of `rb_parser_compile_XXXX()` functions from `rb_ast_t *` to `VALUE`
- `iseq.c` and `vm_core.h`
  - Amend the first parameter of `rb_iseq_new_XXXX()` functions from `rb_ast_body_t *` to `VALUE`
  - This keeps the VALUE of AST on the machine stack to prevent being removed by GC
- `ast.c`
  - Almost all change is replacement `rb_ast_t *ast` with `VALUE vast` (sorry for the big diff)
  - Fix `node_memsize()` to improve memory profiling
    - Now it includes `rb_ast_local_table_link`, `tokens` and `script_lines`
- `compile.c`, `load.c`, `node.c`, `parse.y`, `proc.c`, `ruby.c`, `template/prelude.c.tmpl`, `vm.c` and `vm_eval.c`
  - Follow-up due to the above changes
- `imemo.{c|h}`
  - If an object with `imemo_ast` appears, consider it a bug
  - 👀 If you think the related code should be removed in this PR, please tell me

2024-04-24 08:24 UTC, nobu commented on ast.c
> +    VALUE vast = Qnil;
Does this need to be initialized?

2024-04-24 08:26 UTC, nobu commented on ast.c
> +#define NEW_CHILD(vast, node) node ? ast_new_internal(vast, node) : Qnil
I think a conditional expression macro should be parenthesized.

```suggestion
#define NEW_CHILD(vast, node) (node ? ast_new_internal(vast, node) : Qnil)
```

2024-04-24 08:32 UTC, nobu commented on compile.c
> +    vast = rb_ruby_ast_new(ast);
If `rb_ruby_ast_new` raises an exception, `ast` will be leaked.

2024-04-24 09:00 UTC, nobu requested changes
"Allocate then wrap" is bad, because the "wrapping" itself can fail.
Allocate a wrapped pointer, then fill it.

2024-04-24 17:22 UTC, nobu approved these changes
Looks good.

One more thing.
The usages of `rb_ruby_ast_new` in ruby_parser.c and the outside seem different.
It may be better to separate allocation function (`rb_ruby_ast_alloc` for example) for ruby_parser.c internal usage,  and to pass `root` and `script_lines` arguments to `rb_ruby_ast_new` outside.

2024-04-25 01:18 UTC, hasumikin commented
@nobu 
How about this https://github.com/ruby/ruby/pull/10618/commits/9c3002a3a94e93a2c97f01c34a845858a71b55f9 ?
I wrote `ast_alloc()` instead of `rb_ruby_ast_alloc()` as it's static in ruby_parser.c

2024-04-25 10:20 UTC, nobu commented
Looks good.

2024-04-26 02:17 UTC, yui-knk approved these changes
LGTM!

2024-04-26 02:21 UTC, merged