Fix issue with super and forwarding arguments in prism_compile.c
ruby/ruby pull request #11565
Opened 2024-09-07 16:22 UTC by luke-gru

Fixes [Bug #20720]

2024-09-07 17:50 UTC, luke-gru commented
There's an issue with failing tests now after my change. It's happening in ruby with and without prism enabled, and it's to do with RubyVM::InstructionSequence and code positions. There's a validation of code position ranges that is failing with this code:
 ```ruby
class A
  def m(*args)
    p args
  end
end
class B < A
  def m(...)
    a = nil
    super(a, ...)
  end
end
B.new.m()
```
I could look into it but it would be nice if someone with more experience in the parser could help.

2024-09-11 16:37 UTC, kddnewton requested changes
Thanks @luke-gru!

I've added a flag to the arguments node that should hopefully simplify a lot of the code in this PR. That PR is here: https://github.com/ruby/prism/pull/3051.

Where you currently have to loop through the elements in the argument list, you should now be able to do something like:

```c
bool is_forwardable = (cast->arguments != NULL) && PM_NODE_FLAG_P(cast->arguments, PM_ARGUMENTS_NODE_FLAGS_CONTAINS_FORWARDING);
```

Could you rebase and try that out?

2024-09-11 19:34 UTC, luke-gru commented
Thanks for the flag, that makes it easier. I've rebased and it seems to be working well.

2024-09-11 20:41 UTC, kddnewton approved these changes

2024-09-11 20:41 UTC, merged