Mention `Hash#inspect` changes in NEWS.md
ruby/ruby pull request #11809
Opened 2024-10-05 21:02 UTC by byroot

This will likely cause some incompatibilities in various projects we should try to make it as clear as possible for the next preview release.

cc @tompng

2024-10-05 23:22 UTC, n-rodriguez commented on NEWS.md
> +* `Hash#inspect` rednering have been changed. [[Bug #20433]]
There is a typo here :)

2024-10-07 02:47 UTC, nobu requested changes

2024-10-07 02:47 UTC, nobu commented on NEWS.md
> +* `Hash#inspect` rendering have been changed. [[Bug #20433]]
This needs the following line in the link list at the end of this file.

```
[Bug #20433]:     https://bugs.ruby-lang.org/issues/20433
```

2024-10-07 12:37 UTC, nobu approved these changes

2024-10-07 13:07 UTC, merged