Introduce `RUBY_ASSERT(ruby_thread_has_gvl_p())` to detect invalid interface usage.
ruby/ruby pull request #11975
Opened 2024-11-01 02:46 UTC by ioquatix

2024-11-01 14:28 UTC, jeremyevans requested changes
The zlib changes should be sent upstream to ruby/zlib.  string.c changes look fine.

2024-11-01 14:30 UTC, jeremyevans commented
Never mind, looks like you did submit the changes ro ruby/zlib already: https://github.com/ruby/zlib/pull/88

2024-11-07 00:31 UTC, jeremyevans approved these changes
I recommend updating the commit message to describe that this is being done to debug issues in the zlib extension.  Code changes look fine.

2024-11-07 01:01 UTC, ioquatix commented
The reason why this PR is failing is because `zlib.c` is using the C functions without holding the GVL. Once https://github.com/ruby/zlib/pull/88 is merged, this PR will become green.

2024-11-21 08:21 UTC, ko1 commented on string.c
> +#include "ruby/thread.h"
why does it needed?

2024-11-21 08:23 UTC, ko1 commented
Do you plan to introduce assertions to all of `rb_` prefix C API?

2024-11-21 08:26 UTC, ioquatix commented on string.c
> +#include "ruby/thread.h"
For `ruby_thread_has_gvl_p`.

2024-11-21 08:27 UTC, ioquatix commented
> Do you plan to introduce assertions to all of rb_ prefix C API?

I feel like we should, but it's also quite a lot of work. So for now, my main goal is to find any bugs. Therefore, adding it to methods like `rb_xxx_modify` and so on may be sufficient.

If you have a different idea, please let me know.

2024-11-21 08:28 UTC, ioquatix commented on string.c
> +#include "ruby/thread.h"
Ah yes, I'll fix it.

2024-11-21 08:34 UTC, ioquatix commented on string.c
> +#include "ruby/thread.h"
Okay, it is fixed.

2025-04-14 09:28 UTC, merged

2025-04-29 22:34 UTC, samuel-williams-shopify commented
If you see an error like this:

```
string.c:3660: Assertion Failed: rb_str_set_len:ruby_thread_has_gvl_p()
```

It might mean you are (1) using a build of Ruby that includes this PR, but (2) haven't updated zlib gem to the latest version which does not trigger this assertion.