[DOC] Adjust argument unpacking docs and document **nil
ruby/ruby pull request #12228
Opened 2024-12-01 14:27 UTC by zverok

Motivation: I looked where to put the new `**nil` functionality (as implemented in [Bug #20064](https://bugs.ruby-lang.org/issues/20064)) and found out that the perspective of the unpacking documentation seems to be slightly off. So I adjusted that a bit and added the `#to_a`/`#to_hash` convention, as well as the new `**nil`.

2024-12-01 17:08 UTC, jeremyevans requested changes
This looks mostly good.  There are some typos that need to be fixed, and an important semantic difference that `**nil` does not produce an empty hash, it is just ignored and does not add keywords (it's been optimized to avoid the allocation of an unnecessary hash).

2024-12-01 17:08 UTC, jeremyevans commented on doc/syntax/calling_methods.rdoc
> +operator. In this case, Ruby issues a warning:
```suggestion
operator. In this case, Ruby issues a warning in verbose mode:
```

2024-12-01 17:08 UTC, jeremyevans commented on doc/syntax/calling_methods.rdoc
> +as separate positional arguments:
```suggestion
hashes. If the object responds to a <code>#to_hash</code> method, this method
is called, and is expected to return an Hash, and elements of this hash are passed
as keyword arguments:
```

2024-12-01 17:08 UTC, jeremyevans commented on doc/syntax/calling_methods.rdoc
> +be used in <code>**</code> unpacking, producing an empty hash of keyword arguments.
```suggestion
be used in <code>**</code> unpacking, not adding any keyword arguments.
```

2024-12-01 17:08 UTC, jeremyevans commented on object.c
> + * empty Hash.
```suggestion
 * it can be used in <code>**</code> unpacking, not adding any
 * keyword arguments.
```

2024-12-02 00:01 UTC, nobu commented on doc/syntax/calling_methods.rdoc
> +  my_method *arguments  # warning: `*' interpreted as argument prefix
```suggestion
  my_method *arguments  # warning: '*' interpreted as argument prefix
```

2024-12-02 20:01 UTC, zverok commented
Thank you @jeremyevans @nobu, suggestions applied :pray:

2024-12-02 20:33 UTC, jeremyevans approved these changes

2024-12-15 19:53 UTC, merged