[DOC] Adjust documentation related to backtraces
ruby/ruby pull request #12420
Opened 2024-12-21 17:53 UTC by zverok

Mainly handling the changes made around `Exception#set_backtrace`:
* `error.c`:
  * Adjust documentation for `#set_backtrace`, `#backtrace`, and `#backtrace_locations`;
  * Also adjust examples of errors rendering according to the latest changes throughout the file;
* `doc/exceptions.md`:
  * Adjust documentation in the Backtraces section;
  * Also adjust examples of rendering throughout the file;
* `eval.c`:
  * Adjust `Kernel#raise` documentation.

PS: Just a reminder that English is not my native language, so any suggestions related to syntax, grammar, and wording are totally OK.

2024-12-21 18:52 UTC, byroot commented
Sorry. I don't have the means to review this now nor any time before release. Use your best judgment

2024-12-22 06:06 UTC, nobu commented
The changes of examples look fine.
I'm not sure about descriptions.

2024-12-23 07:02 UTC, jeremyevans requested changes
Most changes look good.  I just have a few recommended wording changes and some typo fixes.

2024-12-23 07:02 UTC, jeremyevans commented on eval.c
> + *  strings or +nil+.
```suggestion
 *  strings, a single string, or +nil+.
```

2024-12-23 07:02 UTC, jeremyevans commented on eval.c
> + *  Using the array of Thread::Backtrace::Location is the most consistent option
```suggestion
 *  Using the array of Thread::Backtrace::Location instances is the most consistent option
```

2024-12-23 20:02 UTC, zverok commented
@jeremyevans Thank you :pray: 
Applied all the suggestions, rebased on the latest `master`, and squashed commits.

2024-12-23 20:05 UTC, Pricer187 commented
What are u wanting me to do

Christopher


On Mon, Dec 23, 2024 at 3:03 PM Victor Shepelev ***@***.***>
wrote:

> @jeremyevans <https://github.com/jeremyevans> Thank you 🙏
> Applied all the suggestions, rebased on the latest master, and squashed
> commits.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ruby/ruby/pull/12420#issuecomment-2560235297>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJKG3LB7TTL42M3X3QT6EX32HBUCVAVCNFSM6AAAAABUA2GFAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRQGIZTKMRZG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-12-24 18:49 UTC, merged

2024-12-24 18:50 UTC, zverok commented
(Sorry, have merged without the final approval to make sure the docs would be there after the release.)

2024-12-24 19:00 UTC, jeremyevans commented
That's fine.  Sorry that I didn't have time to review yesterday.