Object whats here
ruby/ruby pull request #4503
Opened 2021-05-14 17:29 UTC by BurdetteLamar

I know that clone and dup are different, but I don't recall how.

Also, the links to other What's Here sections cite the .html files.  I think this is suboptimal, but could not get them to work otherwise.

2021-05-17 20:13 UTC, BurdetteLamar commented
@jeremyevans, FYI, I have Numeric and Comparable ready for the next PR, but will not be writing from Wednesday through Saturday.

2021-05-17 21:13 UTC, jeremyevans requested changes
Thanks for working on this! Please see inline comments.

2021-05-17 21:13 UTC, jeremyevans commented on object.c
> + *  - #clone::  Returns a shallow copy of +self+.
... `including singleton class and frozen state.`

2021-05-17 21:13 UTC, jeremyevans commented on object.c
> + *  - #dup:: Returns a shallow copy of +self+.
`shallow` -> `shallow unfrozen`

2021-05-17 21:13 UTC, jeremyevans commented on object.c
> + *  - #display:: Prints +self+ to the given \IO stream.
... `or $stdout`.

2021-05-17 21:13 UTC, jeremyevans commented on object.c
> + *  - #enum_for:: Returns an Enumerator for +self+ using the given method,
... `using the given method, arguments, and block`

2021-05-17 21:13 UTC, jeremyevans commented on object.c
> + *  - #to_enum:: Returns an Enumerator for +self+ using the given method,
`to_enum` is an alias of `enum_for`.

2021-05-17 21:13 UTC, jeremyevans commented on object.c
> + *  - #inspect:: Returns a string representation of +self+.
`string` -> `human readable string` (to distinguish from `to_s`)

2021-05-17 21:51 UTC, BurdetteLamar commented on object.c
> + *  - ::const_missing:: Called when an uninitialized constant is referenced.
So remove?

2021-05-17 21:51 UTC, BurdetteLamar commented on object.c
> + *  - ::receive_if:: Receive only a specific message.
So remove?

2021-05-17 22:00 UTC, jeremyevans commented on object.c
> + *  - ::const_missing:: Called when an uninitialized constant is referenced.
Yes, same for `receive_if`.

2021-05-17 22:02 UTC, chrisseaton commented
Aren't these methods already documented? For example what `instance_eval` is now described in two places - `vm_eval.c` and `object.c`. Are we going to make it harder to keep this documentation in sync?

2021-05-17 22:09 UTC, BurdetteLamar commented
> 
> 
> Aren't these methods already documented? For example what `instance_eval` is now described in two places - `vm_eval.c` and `object.c`. Are we going to make it harder to keep this documentation in sync?

#instance_eval and #instance_exec are not in Object doc 3.0.1, so I don't know how they got on my list for the What's Here.  Should these two be removed?  Are there others?

2021-05-17 22:13 UTC, chrisseaton commented
I think I'm more fundamentally confused what you're documenting here - `Object` doesn't define any methods at all!

```
irb(main):001:0> Object.methods(false)
=> []
```

And more generally we're now describing what each method does in two places - and in this case in confusing places that don't actually define the method. Now two places to change if the method changes, and you may not know to look here to do it. Can't we build these summary blocks of what method is in each class automatically? The tools already give you a list of methods - could we annotate the 'summary phrase' short version that you're adding as metadata in the main method documentation and then collate them using a tool?

2021-05-17 22:18 UTC, jeremyevans commented
@chrisseaton Please see the top of https://docs.ruby-lang.org/en/master/Object.html.  It describes that the methods documented for Object are actually implemented in Kernel.  I'm not sure the historical reason for this, but it is deliberately this way.  I would be in favor of documenting everything in Kernel.

In terms of documenting in the same place as the method definition, currently rdoc doesn't support that.  If supported is added to rdoc to enable that, we could potentially use it, but as it doesn't currently exist, that is not currently an option. The only alternative currently would be not having a "What's Here" at all.

2021-05-17 22:22 UTC, BurdetteLamar commented
> 
> 
> I think I'm more fundamentally confused what you're documenting here - `Object` doesn't define any methods at all!
> 
> ```
> irb(main):001:0> Object.methods(false)
> => []
> ```
> 
> And more generally we're now describing what each method does in two places - and in this case in confusing places that don't actually define the method. Now two places to change if the method changes, and you may not know to look here to do it. Can't we build these summary blocks of what method is in each class automatically? The tools already give you a list of methods - could we annotate the 'summary phrase' short version that you're adding as metadata in the main method documentation and then collate them using a tool?

@chrisseaton  For all technical matters, I'm relying on technical reviews by @jeremyevans and others.  As for your last point, I think that would be *much* better, but it's far out-of-scope for me.

2021-05-17 22:22 UTC, jeremyevans commented
@BurdetteLamar `instance_exec` and `instance_eval` you documented in "What's Here" for `BasicObject`, which is correct as that is where they are defined.

2021-05-17 22:26 UTC, BurdetteLamar commented
> 
> 
> @BurdetteLamar `instance_exec` and `instance_eval` you documented in "What's Here" for `BasicObject`, which is correct as that is where they are defined.
Now removed from Object's What's Here.

2021-05-17 23:30 UTC, jeremyevans commented
> > @BurdetteLamar `instance_exec` and `instance_eval` you documented in "What's Here" for `BasicObject`, which is correct as that is where they are defined.
> 
> @jeremyevans, now removed from Object's What's Here.

No, you removed the methods from BasicObject's What's Here.  As I said, those methods were correctly documented in BasicObject, so there was no need to remove them.

2021-05-17 23:35 UTC, jeremyevans requested changes
Looks good. One small new comment, and the previous comment for #clone still needs to be addressed, then it should be ready.

2021-05-17 23:35 UTC, jeremyevans commented on object.c
> + *  - {Methods}[#class-Object-label-Methods]
The `Methods` section was removed.

2021-05-17 23:55 UTC, jeremyevans approved these changes
Looks good!

2021-05-18 13:16 UTC, merged

2021-05-18 17:05 UTC, BurdetteLamar commented
@jeremyevans, I am getting emails about failed checks against this PR.  I can't make out what's wrong.  Some checks were cancelled.  We were clean when I merged 4 hours ago.

2021-05-18 17:23 UTC, jeremyevans commented
You can ignore CI failures for documentation only commits.