Marshal.load: do not call the proc until strings have their encoding
ruby/ruby pull request #4797
Opened 2021-09-01 08:44 UTC by byroot

Ref: https://bugs.ruby-lang.org/issues/18141

2021-09-02 00:43 UTC, byroot commented on spec/ruby/core/marshal/shared/load.rb
> +    ruby_bug "#18141", ""..."3.1"
@nobu I edited like you suggested.

2021-09-02 00:46 UTC, nobu requested changes
This is a bug fix, not a feature change.

2021-09-02 00:46 UTC, nobu commented on spec/ruby/core/marshal/shared/load.rb
> +    ruby_version_is '3.1' do
```suggestion
    ruby_bug "#18141", ""..."3.1" do
```

2021-09-02 00:46 UTC, nobu commented on spec/ruby/core/marshal/shared/load.rb
> +    ruby_version_is '3.1' do
```suggestion
    ruby_bug "#18141", ""..."3.1" do
```

2021-09-02 00:46 UTC, nobu commented on spec/ruby/core/marshal/shared/load.rb
> +      end
```suggestion
```

2021-09-02 08:20 UTC, byroot commented
The Windows build failed, not sure why. All other builds are green.

2021-09-03 16:09 UTC, nobu approved these changes
Why are two `ruby_bug` blocks separated?

2021-09-03 16:09 UTC, nobu commented on spec/ruby/core/marshal/shared/load.rb
> +        string.frozen?.should == true
```suggestion
        string.should.frozen?
```
This is a newer style, and will show a better (or more descriptive) message at failure.

2021-09-04 10:31 UTC, byroot commented
@nobu thanks for the review, I fixed both your comments.

2021-09-05 14:54 UTC, nobu commented
Replacing "loads an Array with proc"  block makes the change clear by `diff -w`, I guess.

2021-09-05 14:59 UTC, byroot commented
> Replacing "loads an Array with proc" block makes the change clear by `diff -w`, I guess.

Not sure I understand what you mean. Are you suggesting further changes to the PR?

2021-09-06 06:30 UTC, nobu commented
> Are you suggesting further changes to the PR?

Sorry, yes.

2021-09-06 06:34 UTC, byroot commented
What change are you suggesting?

2021-09-14 04:38 UTC, nobu commented
I mean, moving the added code to the deleted place.

2021-09-14 12:31 UTC, byroot commented
@nobu done.

2021-09-14 23:00 UTC, merged