marshal.c Marshal.load accepts a `freeze: true` option.
ruby/ruby pull request #4859
Opened 2021-09-17 13:14 UTC by casperisfine

Ref: https://bugs.ruby-lang.org/issues/18148

When set, all the loaded objects are returned as frozen.

If a proc is provided, it is called with the objects already frozen.

2021-09-18 06:22 UTC, nobu requested changes
Could you add tests?

2021-09-18 06:22 UTC, nobu commented on marshal.c
> +    r_fixup_compat(v, arg);
Seems duplication, as this is called in `r_leave` too.
```suggestion
```

2021-09-18 06:22 UTC, nobu commented on marshal.c
> +	} else {
```suggestion
        }
        else if (RB_TYPE_P(v, T_STRING)) {
	    v = rb_str_to_interned_str(v);
	}
	else {
```

2021-09-18 06:22 UTC, nobu commented on marshal.c
> +    return rb_marshal_load_with_proc(port, Qnil, Qfalse);
Passing `Qfalse` as a `bool` may cause a "shortening" warning.
```suggestion
    return rb_marshal_load_with_proc(port, Qnil, false);
```

2021-09-18 13:39 UTC, casperisfine commented
@nobu thank you for the review.

The PR ow heavily changed. I took a step back and first fixed the other bigs from https://bugs.ruby-lang.org/issues/18141 
 (https://github.com/ruby/ruby/pull/4866), which in the end made this feature way easier to implement.

2021-10-01 11:48 UTC, byroot commented
@nobu, I also plan to merge this one in a couple days unless you have concerns.

2021-10-05 16:32 UTC, byroot commented
Merged as Merged as afcbb501ac17ba2ad5370ada5fd26e8dda9a5aaa

2021-10-05 16:32 UTC, closed without merging