Enhanced RDoc for Enumerable
ruby/ruby pull request #4908
Opened 2021-09-28 19:40 UTC by BurdetteLamar

Treated:
- #none?
- #one?
- #min

2021-09-28 21:22 UTC, jeremyevans requested changes
Looks good!  Only one minor change requested, OK to merge after that.

2021-09-28 21:22 UTC, jeremyevans commented on enum.c
> + *  using the elements' own method <tt>=></tt> for comparison:
`=>` => `<=>`

2021-09-28 21:28 UTC, BurdetteLamar commented on enum.c
> + *  using the elements' own method <tt>=></tt> for comparison:
Done.

2021-09-28 23:20 UTC, merged

2021-09-29 22:37 UTC, JuPlutonic commented on enum.c
> + *    {foo: 0, bar: 1, baz: 2}.one? {|key, value| value < 2  } # => false
extra space in block `{|key, value| value < 2 }`

2021-09-29 22:39 UTC, JuPlutonic commented on enum.c
> + *    {foo: 0, bar: 1, baz: 2}.none? {|key, value| value < 1  } # => false
extra space

2021-09-29 22:44 UTC, JuPlutonic commented on enum.c
> + *  Related: #.one?, #all?, #any.
correction:
`#one?`, not `#.one?`
`#any?`, not `#any`

2021-09-29 23:19 UTC, JuPlutonic commented on enum.c
> + *    [].min {|a, b| a <=> b }                          # => nil
suggestion:
{foo: 0, bar: 1, baz: 2}.min {|pair1, pair2| pair1[1] <=> pair2[1] }
=> [[:foo, 0], [:bar, 1]]

2021-09-29 23:20 UTC, JuPlutonic commented on enum.c
> + *    [].min(2) {|a, b| a <=> b }                          # => []
{foo: 0, bar: 1, baz: 2}.min(2) {|pair1, pair2| pair1[1] <=> pair2[1] }
=> [[:foo, 0], [:bar, 1]]

2021-09-30 00:03 UTC, JuPlutonic commented on enum.c
> + *    %w[xxx x xxxx xx].min(2) {|a, b| a.size <=> b.size } # => ["x", "xx"]
suggestion:
```ruby
{foo: 0, bar: 1, baz: 2}.min(2) {|pair1, pair2| pair1[1] <=> pair2[1] }
# => [[:foo, 0], [:bar, 1]]
```

2021-09-30 00:04 UTC, JuPlutonic commented on enum.c
> + *    %w[xxx x xxxx xx].min {|a, b| a.size <=> b.size } # => "x"
suggestion:
```ruby
{foo: 0, bar: 1, baz: 2}.min {|pair1, pair2| pair1[1] <=> pair2[1] }
# => [:foo, 0]
```