Add `nd_type_p` macro
ruby/ruby pull request #5091
Opened 2021-11-08 12:26 UTC by S-H-GAMELINKS

MRI has these code using `nd_type` macro to check NODE type.

```c
static NODE *
rest_arg_append(struct parser_params *p, NODE *args, NODE *rest_arg, const YYLTYPE *loc)
{
    NODE *n1;
    if ((nd_type(rest_arg) == NODE_LIST) && (n1 = splat_array(args)) != 0) {
	return list_concat(n1, rest_arg);
    }
    return arg_concat(p, args, rest_arg, loc);
}
```

However, conditions will be long and sometimes difficult to read, I think.

So, I think better to introduce `nd_type_p` macro like this.

```h
#define nd_type_p(n, t) (nd_type((n)) == (t))
```

I think that conditions can be more shorter to using `nd_type_p` macro.
How about it？

```c
static NODE *
rest_arg_append(struct parser_params *p, NODE *args, NODE *rest_arg, const YYLTYPE *loc)
{
    NODE *n1;
    if ((nd_type_p(rest_arg, NODE_LIST)) && (n1 = splat_array(args)) != 0) {
	return list_concat(n1, rest_arg);
    }
    return arg_concat(p, args, rest_arg, loc);
}
```

2021-11-08 13:31 UTC, nobu requested changes

2021-11-08 13:31 UTC, nobu commented on parse.y
> +    if (left && (enum node_type)nd_type_p(left, type)) {
```suggestion
    if (left && nd_type_p(left, type)) {
```

2021-11-08 13:31 UTC, nobu commented on parse.y
> +	while ((second = node->nd_2nd) != 0 && (enum node_type)nd_type_p(second, type)) {
```suggestion
	while ((second = node->nd_2nd) != 0 && nd_type_p(second, type)) {
```

2021-11-08 13:31 UTC, nobu commented on node.c
> +	    if (!node->nd_2nd || !nd_type_p(node->nd_2nd, (int)type))
```suggestion
	    if (!node->nd_2nd || !nd_type_p(node->nd_2nd, type))
```

2021-11-08 13:34 UTC, nobu commented
Another `nd_type() == NODE_...` is in a comment at compile.c:1784.

2021-11-08 13:45 UTC, S-H-GAMELINKS commented
@nobu 
Thank you for your review.
I fixed code that you review pointed out in this pull request.

2021-11-08 14:09 UTC, nobu approved these changes

2021-12-01 12:47 UTC, S-H-GAMELINKS commented
Rebased to latest master(a84dc9d80d41db01db4623517ade928ee7f40e36) branch.

2021-12-03 15:01 UTC, merged