Enhanced RDoc for Integer
ruby/ruby pull request #5118
Opened 2021-11-15 17:21 UTC by BurdetteLamar

Treats:

    #allbits?
    #anybits?
    #nobits?
    #succ
    #pred
    #chr`
    #to_s
    #+
    #-

This is a replacement for the merged-then-reverted PR [5099](https://github.com/ruby/ruby/pull/5099), which had an offending character in a C-code comment (from an irb example).  The containing RDoc is now moved out of numeric.c and into numeric.rb, which I hope will be ok.

2021-11-15 17:46 UTC, jeremyevans requested changes
I did some more research into the `chr` method, and think the documentation should be fixed for it.  It's probably best to fix the documentation, but still include the fixed documentation in the `numeric.c` file, for consistency.  Only methods defined in `numeric.rb` should be documented there.

2021-11-15 18:41 UTC, BurdetteLamar commented on numeric.rb
> +  #     255.chr(Encoding::UTF_8) # => "ÿ"
Done.

2021-11-15 18:41 UTC, BurdetteLamar commented on numeric.rb
> +  #    chr(encoding = Encoding.default_internal) -> string
Done.

2021-11-15 19:15 UTC, jeremyevans approved these changes
Looks good!

2021-11-15 19:52 UTC, merged

2021-11-16 01:10 UTC, ioquatix commented
TY!