Enhanced RDoc for IO.popen
ruby/ruby pull request #5430
Opened 2022-01-11 21:56 UTC by BurdetteLamar

This is tough.

2022-01-11 23:05 UTC, jeremyevans requested changes
Looks mostly good, please see requested changes.

2022-01-12 14:42 UTC, BurdetteLamar commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
@jeremyevans, you're referring to this?
-   `[env, [cmdname, argv0], arg1, ..., opts] : command name, argv[0] and zero or more arguments (no shell)`
I don't understand ths form.  Wouldn't arg1 have to be mode?  And what does the ellipsis mean?

2022-01-12 16:09 UTC, jeremyevans commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
I think the previous code example is wrong.  You can pass arguments without using a shell using an array: `IO.popen(['cmd', 'arg1', 'arg2'])`.  You can set argv0 by making the first element of this array be an array with the command and desired argv0: `IO.popen([['cmd', 'argv0'], 'arg1', 'arg2'])`

2022-01-12 17:22 UTC, BurdetteLamar commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
Ok, I have this:

File.write('t.rb', '$stderr.puts ARGV')# => 17
IO.popen([['ruby', 'argv0'], 't.rb', 'FOO', 'BAR'])# => #<IO:fd 5>
FOO
BAR

What is `argv0` doing?

2022-01-12 17:28 UTC, jeremyevans commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
`argv0` sets `argv[0]` when running the program.  Some programs access `argv[0]` and operate differently depending on the value.  For example, on my system, `tar` and `pax` are the same program, and whether it operates as `tar` or `pax` depends on `argv[0]`.

2022-01-12 17:58 UTC, BurdetteLamar commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
I'm still missing something:

File.write('t.rb', '$stderr.puts argv[0]') # => 20
IO.popen([['ruby', 'argv0'], 't.rb', 'FOO', 'BAR']) # => #<IO:fd 5>
t.rb:1:in `<main>': undefined local variable or method `argv' for main:Object (NameError)

2022-01-12 18:28 UTC, jeremyevans commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
I don't think Ruby provides access to `argv[0]`, so it isn't a good program to test with.  Try using a shell:

```
$ ruby -e 'puts IO.popen(["/bin/sh", "-c", "echo $0"]).read'
/bin/sh
$ ruby -e 'puts IO.popen([["/bin/sh", "foo"], "-c", "echo $0"]).read'
foo
```

2022-01-12 22:26 UTC, BurdetteLamar commented on io.c
> + *  - An array of strings: Runs a Ruby subprocess with the array as its ARGV.
Fixed?

2022-01-12 22:26 UTC, BurdetteLamar commented on io.c
> + *  <b>Ruby Subprocess</b>
Fixed.

2022-01-12 22:26 UTC, BurdetteLamar commented on io.c
> - *  At the end of block, Ruby closes the pipe and sets <code>$?</code>.
Now mentioned near the top.

2022-01-12 22:27 UTC, BurdetteLamar commented on io.c
> - *  then it will be used as the subprocess's +argv+ bypassing a shell.
Fixed?

2022-01-12 23:07 UTC, jeremyevans approved these changes
Looks good!

2022-01-12 23:08 UTC, merged