[DOC] Fix links in documentation for File and IO
ruby/ruby pull request #5530
Opened 2022-02-05 19:34 UTC by peterzhu2118

Fixes some typos and dead links.

2022-02-05 21:43 UTC, BurdetteLamar approved these changes

2022-02-06 05:17 UTC, nobu requested changes
Same for other URL links.

2022-02-06 05:17 UTC, nobu commented on file.c
> + *  See {IO Modes}[IO.html#class-IO-label-Modes].
RDoc provides link notation to sections, as well as methods.
```suggestion
 *  See IO@Modes.
```
I think this is much preferable than the generated file name and section name.

2022-02-06 05:17 UTC, nobu commented on io.c
> + *  see {\IO Modes}[IO.html#class-IO-label-Modes]:
```suggestion
 *  see IO@Modes:
```

2022-02-06 05:17 UTC, nobu commented on io.c
> + *  see {File Permissions}[#class-File-label-File+Permissions]:
Also this kind of error won't occur.
```suggestion
 *  see File@Permissions:
```

2022-02-06 05:17 UTC, nobu commented on io.c
> + *  see {IO Open Options}[IO.html#class-IO-label-Open+Options]:
```suggestion
 *  see IO@Open+Options:
```

2022-02-06 19:27 UTC, BurdetteLamar commented
Re-approved.

2022-02-07 05:01 UTC, nobu commented on file.c
> + *  See {IO Modes}[rdoc-ref:IO@Modes].
Isn't `IO@Modes` just enough?

2022-02-07 14:06 UTC, peterzhu2118 commented on file.c
> + *  See {IO Modes}[rdoc-ref:IO@Modes].
Fixed.

2022-02-07 14:52 UTC, merged

2022-02-07 15:24 UTC, nobu commented
Seems no `What's Here` sections in `Enumerable` and `FileTest`. 🤷

2022-02-07 15:44 UTC, nobu commented on array.c
> + *  - {And more....}[rdoc-ref:Array@Other+Methods]
In the same namespace, the class name `Array` should be able to omit.