[DOC] Chang to guidance on lists in What's Here section
ruby/ruby pull request #5618
Opened 2022-03-02 20:40 UTC by BurdetteLamar

Currently, the guide says What's Here should have labeled list for method.  Such a list can render very differently in different browsers, and are often erratic in their indentation of continuation lines.

The proposed guidance is to use a bullet list.

2022-03-02 21:37 UTC, jeremyevans requested changes
I've always disliked RDoc's use of dl/dt/dd for labeled lists.  Even if it is semantically better, it generally doesn't look good.  A table-based approach, while not as good semantically, generally looks better.  However, unless we can change RDoc, switching to a simple list seems best.

In terms of the text, after two small typo fixes, this can be committed after a couple days unless someone objects.  I want to allow more time here because this is changing the guide for writing documentation, so it's a change in our process and we should allow more time for comment/review.

2022-03-02 21:37 UTC, jeremyevans commented on doc/documentation_guide.rdoc
> +- If there are numerout entries, consider gouping them into subsections with headers.
s/numerout/numerous/
s/gouping/grouping/

2022-03-02 21:49 UTC, BurdetteLamar commented on doc/documentation_guide.rdoc
> +- If there are numerout entries, consider gouping them into subsections with headers.
Fixed.

2022-03-04 19:44 UTC, jeremyevans approved these changes

2022-03-07 11:04 UTC, merged