Reuse `rb_proc_arity`
ruby/ruby pull request #5823
Opened 2022-04-19 04:27 UTC by S-H-GAMELINKS

`rb_block_arity` has same code in part as `rb_proc_arity`.
Better to reuse `rb_proc_arity`,  I think.

2022-04-22 22:15 UTC, jeremyevans requested changes
I'm guessing the current implementation is an attempt to avoid calling `rb_vm_block_min_max_arity` twice.  So you may want to move the preceding `rb_vm_block_min_max_arity` call in this function to the `default:` case.

Additionally, I think you can use `rb_proc_arity(block_handler)`, as I don't see a need for the `procval` local variable.

2022-04-23 01:22 UTC, S-H-GAMELINKS commented
@jeremyevans 
Thanks for youre comment!

>I'm guessing the current implementation is an attempt to avoid calling rb_vm_block_min_max_arity twice. So you may want to move the preceding rb_vm_block_min_max_arity call in this function to the default: case.
>
>Additionally, I think you can use rb_proc_arity(block_handler), as I don't see a need for the procval local variable.

Fixed this change in https://github.com/ruby/ruby/pull/5823/commits/88a080023bafa5ccbb47d1b861333d15c51edb3c

2022-04-23 01:27 UTC, jeremyevans approved these changes
Looks good.  I think you can also remove the braces in the `block_handler_type_proc` case, since they are no longer needed.  But this should be good to merge if it passes CI.

2022-04-23 02:07 UTC, S-H-GAMELINKS commented
>I think you can also remove the braces in the block_handler_type_proc case, since they are no longer needed

I tried in local environment to remove the brace in the block_handler_type_proc case, and passed test (so push this commit https://github.com/ruby/ruby/pull/5823/commits/2c45ed7b342958537c719adb4f9c907289c82833).

2022-04-24 21:06 UTC, merged