[DOC] Enhanced RDoc for File
ruby/ruby pull request #5861
Opened 2022-04-28 22:15 UTC by BurdetteLamar

Treats:
- ::pipe?
- ::symlink?
- ::socket?
- ::blockdev?
- ::chardev?
-

2022-04-28 22:28 UTC, jeremyevans requested changes

2022-04-28 22:28 UTC, jeremyevans commented on file.c
> + * Returns +true+ if +object+ is a pipe, +false+ otherwise:
The main use of `File.pipe?` is with file names, though it does also support IO objects.  There should be a description and examples for use with file names (pipes in the file system can be created with `File.mkfifo`).

Similar issue for `File.socket?`

2022-04-28 22:28 UTC, jeremyevans commented on file.c
> - *   File.pipe?(file_name)   ->  true or false
For all of these methods, they are primarily called with filenames, so the argument in the call-seq should remain `file_name`.

2022-04-28 22:46 UTC, BurdetteLamar commented
@jeremyevans, there's a lot in File that I don't understand very well.  I'd like to close this and find something else to work on.  (Any suggestions?)

2022-04-28 22:58 UTC, jeremyevans commented
> @jeremyevans, there's a lot in File that I don't understand very well. I'd like to close this and find something else to work on. (Any suggestions?)

Closing this is fine. I don't have any suggestions currently.

2022-04-29 18:37 UTC, BurdetteLamar commented
Re-opening this, because it's time I learned more about class File and its methods.

2022-05-04 12:21 UTC, BurdetteLamar commented
I thought I had re-opened this already (and the thingy says so above).

2022-05-05 20:01 UTC, BurdetteLamar commented
Rolled forward to https://github.com/ruby/ruby/pull/5888.

2022-05-05 20:01 UTC, closed without merging