Clarification for offset and timezone in Time
ruby/ruby pull request #6291
Opened 2022-08-27 22:38 UTC by BurdetteLamar

Distinguishes between time offset and timezone.

This is not a [DOC] PR because it  changes a parameter name in one method.

2022-08-27 23:51 UTC, nobu commented
`zone` arguments accept also timezone names if a suitable library is loaded.

2022-08-28 00:02 UTC, jeremyevans requested changes
See inline comment.  Considering that all of these places actually do accept an appropriate timezone argument, I'm not sure any of these changes are desirable.

Example of timezone usage, using the `tzinfo` library (which exposes an appropriate timezone object):

```ruby
require 'tzinfo'
Time.now.localtime(TZInfo::Timezone.get('America/Los_Angeles'))
# => 2022-08-27 16:52:28.268233031 -0700
Time.now.localtime(TZInfo::Timezone.get('Japan'))
# => 2022-08-28 08:52:39.340482787 +0900
```

The `timezone` gem also offers an appropriate timezone object that `Time` can use.

2022-08-28 17:14 UTC, BurdetteLamar commented on doc/time_offsets.rdoc
> +- Time#localtime: positional argument +offset+.
The fourth list item following both mentions and links to the timezone object.  Not sure it matters, though, because I'll be closing this PR.

2022-08-28 17:15 UTC, BurdetteLamar commented
It's not all apparent from the Time doc that string timezone names are accepted in most of these places.  I'll need to study more, then see what I can do.

2022-08-28 17:15 UTC, closed without merging

2022-08-29 16:58 UTC, BurdetteLamar commented
> See inline comment. Considering that all of these places actually do accept an appropriate timezone argument, I'm not sure any of these changes are desirable.
> 
> Example of timezone usage, using the `tzinfo` library (which exposes an appropriate timezone object):
> 
> ```ruby
> require 'tzinfo'
> Time.now.localtime(TZInfo::Timezone.get('America/Los_Angeles'))
> # => 2022-08-27 16:52:28.268233031 -0700
> Time.now.localtime(TZInfo::Timezone.get('Japan'))
> # => 2022-08-28 08:52:39.340482787 +0900
> ```
> 
> The `timezone` gem also offers an appropriate timezone object that `Time` can use.

@jeremyevans when I `require 'tzinfo'` (gem `tzinfo` not installed), I get a LoadError.  Is that library different from the eponymous gem?

2022-08-29 17:00 UTC, jeremyevans commented
You might also need the `tzinfo-data` gem, if the `tzinfo` gem cannot find the timezone information on your system.

2022-08-29 17:18 UTC, BurdetteLamar commented
Different question:  you're example above had `require tzinfo` (no mention of the gem);  when I do that (w/o the gem) I get an error.  Should that work?  Or do I need the gem in all cases?

2022-08-29 17:48 UTC, jeremyevans commented
If you want to use tzinfo, you do need the tzinfo gem installed. However, Ruby itself does not require any specific gems for timezones, it only requires that the timezone object you use responds to specific methods (documented in the Time class documentation).  tzinfo and timezone are both gems that implement timezone objects with these methods.  However, you could create your own timezone object that also responds to the methods appropriately, and that would work as well.