Support invoke super on more method types
ruby/ruby pull request #6726
Opened 2022-11-14 16:03 UTC by jimmyhmiller

2022-11-18 18:59 UTC, maximecb commented on yjit/src/codegen.rs
> +
```suggestion
```

2022-11-18 18:59 UTC, maximecb commented on yjit/src/codegen.rs
> +
```suggestion
```

2022-11-18 19:01 UTC, maximecb reviewed
Code looks good, but could you include the railsbench stats before/after ?

2022-11-18 19:12 UTC, noahgibbs commented on yjit/src/codegen.rs
> +
Similarly, probably don't need these 3 extra lines of whitespace.

2022-11-18 19:34 UTC, maximecb commented
> Do you know if we already have a test that hits using an alias via super()?

👍 always good to be extra super diligent if we don't have such a test.

2022-11-18 19:40 UTC, XrXr requested changes
There is a behavior difference:
```ruby
# review for 5516bf4580da2b692d68b10b3734f04e3adeba7a Support invoke super on more method types

class Parent
  attr_accessor :foo
end

class Splat < Parent
  def foo=(arg)
    super(*arg)
  end
end

s = Splat.new
s.foo = [100]
p s.foo # 100 in interpreter, [100] with YJIT
```
You need to replicate this check I think:
https://github.com/ruby/ruby/blob/ba3b40a9aeb752d1b3e4c87748c977bfd3cf6f2c/yjit/src/codegen.rs#L5300-L5303
Since we're close to the release I'm a bit nervous about other things I might've missed, but maybe it's fine.

2022-11-18 19:40 UTC, XrXr commented on yjit/src/codegen.rs
> +
```suggestion
```

2022-11-21 15:12 UTC, jimmyhmiller commented
Closing since we are close to release Can revisit some other time.

2022-11-21 15:12 UTC, closed without merging