Fix small issues concerning namespacing in test-all suite
ruby/ruby pull request #7513
Opened 2023-03-13 22:18 UTC by luke-gru

* Fix temporary methods on Object or Kernel leaking across test cases.
* Fix rescue NameError/LoadError over entire file when want to rescue for 1 require only

2023-03-13 22:18 UTC, luke-gru commented on test/irb/yamatanooroti/test_rendering.rb
> +rescue LoadError, NameError
The diff for this file without whitespace is just this rescue block

2023-03-13 22:26 UTC, luke-gru commented
For the IRB test file, I wasn't sure if I needed to modify it in the IRB repo, or if changes could go in both directions (that is, can be modified here first and then the maintainer cherry-picks the changes). If it's the first one, then I can re-push without the IRB changes.

2023-03-14 01:44 UTC, hsbt requested changes
Can you submit `irb` tests to https://github.com/ruby/irb?

2023-03-15 16:30 UTC, luke-gru commented
Yes I will submit those changes separately to IRB. I've updated the branch 👍

2023-03-16 23:27 UTC, hsbt approved these changes

2023-03-16 23:46 UTC, merged

2023-03-16 23:46 UTC, hsbt commented
@luke-gru Thanks!