[DOC] Fix links to non-existent pages
ruby/ruby pull request #7978
Opened 2023-06-24 16:58 UTC by BurdetteLamar

Fixes the links I've found that link to non-existent pages (but not those with incorrect fragments):

- When I could find a useful substitute page, I've changed the link.
- When not, I've removed the link.
- In one file, the links were (I think) unintended;  I've moved that text  (code, actually) into code blocks.

2023-06-24 17:08 UTC, nobu commented on README.ja.md
> +[COPYING.ja](https://docs.ruby-lang.org/en/master/COPYING_ja.html   ) ファイルを参照してください．
```suggestion
[COPYING.ja](https://docs.ruby-lang.org/en/master/COPYING_ja.html) ファイルを参照してください．
```

2023-06-24 17:10 UTC, nobu commented
Old files and cited LEGAL should be untouched, I think.

2023-06-24 17:51 UTC, peterzhu2118 requested changes
I don't think we should change release notes for old Rubies.

2023-06-24 20:21 UTC, BurdetteLamar commented
Ok.  So we ignore `LEGAL` and `doc/NEWS/`.  Can anyone think of others, going forward?

2023-06-24 22:33 UTC, BurdetteLamar commented
If no one objects, I'll close this and open a new PR without the offending changes.

2023-06-25 13:10 UTC, BurdetteLamar commented
> If no one objects, I'll close this and open a new PR without the offending changes.

Doing so now.

2023-06-25 13:10 UTC, closed without merging