Add __owner__
ruby/ruby pull request #8411
Opened 2023-09-10 15:01 UTC by konsolebox

For https://bugs.ruby-lang.org/issues/19871.

2023-09-10 15:23 UTC, nobu requested changes
You will need tests, at least.

2023-09-10 15:23 UTC, nobu commented on eval.c
> +    rb_callable_method_entry_t *me = rb_vm_frame_method_entry(prev_cfp);
```suggestion
    const rb_callable_method_entry_t *me = rb_vm_frame_method_entry(prev_cfp);
```

2023-09-10 15:42 UTC, konsolebox commented
> You will need tests, at least.

I'll try to add them asap.

2023-09-11 17:58 UTC, konsolebox reviewed
Already applied

2023-09-11 18:53 UTC, konsolebox commented
> You will need tests, at least.

I just added the spec but it's failing in "Rubyspec Version Guards Check / Rubyspec (ruby-3.2) (pull_request)".  Should this one be fixed as well?

2023-09-12 10:10 UTC, konsolebox commented
So apparently a constant can't be shadowed by an inheriting class when it's expanded without a scope, so I'll just close this for now until another use case needs it.

2023-09-12 10:10 UTC, closed without merging