[YARP] Implement MatchLastLineNode
ruby/ruby pull request #8479
Opened 2023-09-19 19:29 UTC by eileencodes

This PR implements `MatchLastLineNode` for YARP.

Related: https://github.com/ruby/yarp/issues/1335

2023-09-19 19:35 UTC, jemmaissroff approved these changes

2023-09-27 15:27 UTC, kddnewton requested changes

2023-09-27 15:27 UTC, kddnewton commented on yarp/yarp_compiler.c
> +              ADD_SEND(ret, &dummy_line_node, rb_intern("=~"), INT2NUM(1));
```suggestion
              ADD_SEND(ret, &dummy_line_node, idEqTilde, INT2NUM(1));
```

2023-09-27 15:30 UTC, eileencodes commented on yarp/yarp_compiler.c
> +              ADD_SEND(ret, &dummy_line_node, rb_intern("=~"), INT2NUM(1));
Done and amended the commit.

2023-09-27 19:31 UTC, kddnewton commented
Sorry I totally messed you up by merging the rename. This is going to need a rebase, then good to go.

2023-09-27 20:56 UTC, eileencodes commented
>  Sorry I totally messed you up by merging the rename. This is going to need a rebase, then good to go.

No worries, I rewrote it, should be good to go now. 👍🏼

2023-09-27 22:36 UTC, kddnewton approved these changes

2023-09-27 22:36 UTC, merged