[Prism] Compile ForNode
ruby/ruby pull request #8722
Opened 2023-10-20 10:19 UTC by eightbitraptor

Fixes https://github.com/ruby/prism/issues/1648

This currently supports ForNodes with a single instance variable. Multiple assigments aren't fully implemented yet.

eg.

```
for i, j in {a: 'b'} do
  puts i
  puts j
end
```

will result in a stack underflow.

2023-10-20 11:48 UTC, nobu commented on prism_compile.c
> +          pm_for_node_t *for_node = (pm_for_node_t *)node;
This block is not aligned as the others.

2023-10-20 13:04 UTC, jemmaissroff requested changes

2023-10-20 13:04 UTC, jemmaissroff commented on compile.c
> +    pm_constant_id_list_t *locals = &((pm_scope_node_t *) scope_node)->locals;
Is the `(pm_scope_node_t *)` cast necessary?

2023-10-21 10:15 UTC, nobu commented on compile.c
> +    }
Isn't this prism internal?
If so, shouldn't be done in `rb_translate_prism`?

2023-10-30 14:20 UTC, jemmaissroff approved these changes

2023-10-30 14:33 UTC, kddnewton requested changes
What an achievement! Great work! One small comment

2023-10-30 16:19 UTC, eightbitraptor commented on prism_compile.c
> +#define TEMP_CONSTANT_IDENTIFIER ((pm_constant_id_t)(1 << 31))
Sounds good. I should probably think of a better name too!

2023-10-30 18:44 UTC, kddnewton approved these changes

2023-10-30 19:44 UTC, merged