[PRISM] Implement opt_aset_with
ruby/ruby pull request #9820
Opened 2024-02-02 22:02 UTC by jenshenny

Part of https://github.com/ruby/prism/issues/2231

2024-02-02 22:11 UTC, kddnewton requested changes
This looks good!

Question: I think `"foo"&.freeze` might be incorrectly using optimizations now, because it's not checked unless I'm misreading?

2024-02-04 00:29 UTC, jenshenny commented
> Question: I think "foo"&.freeze might be incorrectly using optimizations now, because it's not checked unless I'm misreading?

Yeah good catch, when checking Ruby's instruction sequence with freeze, -@, aref and aset, they aren't using optimizations. Added the check here and opened a PR to fix the other cases as well https://github.com/ruby/ruby/pull/9826

2024-02-04 16:05 UTC, kddnewton requested changes

2024-02-04 16:05 UTC, kddnewton commented on prism_compile.c
> +        if ((method_id == idUMinus || method_id == idFreeze) &&
I think we need the safe navigation check here as well.

2024-02-05 15:15 UTC, kddnewton approved these changes

2024-02-05 15:27 UTC, merged